# Generated by Django 5.1.7 on 2025-04-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0006_perfilalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='materias_inscritas',
            field=models.ManyToManyField(related_name='alumnos', to='Restaurante.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='Restaurante.docente'),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='Restaurante.alumno'),
        ),
    ]
