# Generated by Django 5.1.7 on 2025-04-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0010_alter_materia_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='Restaurante.docente'),
        ),
    ]
