# Generated by Django 5.1.7 on 2025-04-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0012_alter_materia_docente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
