# Generated by Django 5.1.7 on 2025-04-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0013_rename_apellidos_docente_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilalumno',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='docente',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='PerfilAlumno',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
