# Generated by Django 5.1.7 on 2025-04-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0014_remove_perfilalumno_alumno_remove_materia_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='mesas',
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurante.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurante.mesa'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurante.mesero'),
        ),
    ]
