# Generated by Django 5.1.7 on 2025-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0015_remove_orden_mesas_orden_cliente_orden_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='en proceso', max_length=10),
        ),
    ]
