# Generated by Django 5.1.7 on 2025-04-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0016_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='En Proceso', max_length=10),
        ),
    ]
