# Generated by Django 5.1.7 on 2025-04-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0019_alter_orden_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='platos',
        ),
        migrations.CreateModel(
            name='OrdenPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.orden')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.plato')),
            ],
        ),
    ]
