# Generated by Django 5.1.7 on 2025-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0020_remove_orden_platos_ordenplato'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='platos',
            field=models.ManyToManyField(to='Restaurante.plato'),
        ),
        migrations.DeleteModel(
            name='OrdenPlato',
        ),
    ]
